二维离散卷积运算，使用scipy库中的signal.convolve2d函数

SciPy函数库在NumPy库的基础上增加了线性代数、常微分方程数值求解、信号处理、图像处理、稀疏矩阵等等

In [4]:
# -*- coding: utf-8 -*-
import numpy as np
from scipy import signal

I = np.array([[1,2],[3,4]],np.float32)
#高宽
H1,W1 = I.shape[:2]
#卷积核
K = np.array([[-1,-2],[2,1]],np.float32)
#K的高和宽
H2,W2 = K.shape[:2]

#计算full卷积
c_full = signal.convolve2d(I,K,mode='full')
#指定锚点位置
kr,kc = 0,0
#根据锚点位置，从full卷积中截取得到same卷积
c_same = c_full[H2-kr-1:H1+H2-kr-1,W2-kc-1:W1+W2-kc-1]

5.1.2 可分离卷积

一个卷积核可由多个小的卷积核full卷积而成，边界均进行扩充零操作。

In [9]:
# -*- coding: utf-8 -*-
import numpy as np
from scipy import signal

kernel1 = np.array([[1,2,3]],np.float32)
kernel2 = np.array([[4],[5],[6]],np.float32)

kernel = signal.convolve2d(kernel1,kernel2,mode='full')
print kernel

[[ 4.  8. 12.]
 [ 5. 10. 15.]
 [ 6. 12. 18.]]
